DROP TABLE IF EXISTS abilites CASCADE;
DROP TABLE IF EXISTS game_instances CASCADE;
DROP TABLE IF EXISTS player_characters CASCADE;
DROP TABLE IF EXISTS characters CASCADE;
DROP TABLE IF EXISTS items CASCADE;
DROP TABLE IF EXISTS player_items CASCADE;
DROP TABLE IF EXISTS game_log CASCADE;
DROP TABLE IF EXISTS chat CASCADE;